version: '3.8'

services:
  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    volumes:
      - ipc-socket:/tmp
    ports:
      - "514:514/udp" # Syslog ingestion port
      - "8080:8080"   # HTTP ingestion port

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - GO_SOCKET_PATH=/tmp/logengine.sock
      - JWT_SECRET=hackathon_secret_2026
    volumes:
      - ipc-socket:/tmp
    ports:
      - "3001:3001"
    depends_on:
      - engine

volumes:
  ipc-socket: # Shared volume where /tmp/logengine.sock lives