// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/logservice.proto

package logengine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	StartTimeNano int64                  `protobuf:"varint,2,opt,name=start_time_nano,json=startTimeNano,proto3" json:"start_time_nano,omitempty"`
	EndTimeNano   int64                  `protobuf:"varint,3,opt,name=end_time_nano,json=endTimeNano,proto3" json:"end_time_nano,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_logservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_logservice_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *QueryRequest) GetStartTimeNano() int64 {
	if x != nil {
		return x.StartTimeNano
	}
	return 0
}

func (x *QueryRequest) GetEndTimeNano() int64 {
	if x != nil {
		return x.EndTimeNano
	}
	return 0
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNano int64                  `protobuf:"varint,1,opt,name=timestamp_nano,json=timestampNano,proto3" json:"timestamp_nano,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_logservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logservice_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTimestampNano() int64 {
	if x != nil {
		return x.TimestampNano
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalFound    int64                  `protobuf:"varint,2,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_logservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_logservice_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryResponse) GetTotalFound() int64 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_logservice_proto protoreflect.FileDescriptor

const file_proto_logservice_proto_rawDesc = "" +
	"\n" +
	"\x16proto/logservice.proto\x12\tlogengine\"\x84\x01\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12&\n" +
	"\x0fstart_time_nano\x18\x02 \x01(\x03R\rstartTimeNano\x12\"\n" +
	"\rend_time_nano\x18\x03 \x01(\x03R\vendTimeNano\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"K\n" +
	"\bLogEntry\x12%\n" +
	"\x0etimestamp_nano\x18\x01 \x01(\x03R\rtimestampNano\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"o\n" +
	"\rQueryResponse\x12'\n" +
	"\x04logs\x18\x01 \x03(\v2\x13.logengine.LogEntryR\x04logs\x12\x1f\n" +
	"\vtotal_found\x18\x02 \x01(\x03R\n" +
	"totalFound\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x87\x01\n" +
	"\n" +
	"LogService\x12:\n" +
	"\x05Query\x12\x17.logengine.QueryRequest\x1a\x18.logengine.QueryResponse\x12=\n" +
	"\vStreamQuery\x12\x17.logengine.QueryRequest\x1a\x13.logengine.LogEntry0\x01B\x18Z\x16engine/proto/logengineb\x06proto3"

var (
	file_proto_logservice_proto_rawDescOnce sync.Once
	file_proto_logservice_proto_rawDescData []byte
)

func file_proto_logservice_proto_rawDescGZIP() []byte {
	file_proto_logservice_proto_rawDescOnce.Do(func() {
		file_proto_logservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logservice_proto_rawDesc), len(file_proto_logservice_proto_rawDesc)))
	})
	return file_proto_logservice_proto_rawDescData
}

var file_proto_logservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_logservice_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: logengine.QueryRequest
	(*LogEntry)(nil),      // 1: logengine.LogEntry
	(*QueryResponse)(nil), // 2: logengine.QueryResponse
}
var file_proto_logservice_proto_depIdxs = []int32{
	1, // 0: logengine.QueryResponse.logs:type_name -> logengine.LogEntry
	0, // 1: logengine.LogService.Query:input_type -> logengine.QueryRequest
	0, // 2: logengine.LogService.StreamQuery:input_type -> logengine.QueryRequest
	2, // 3: logengine.LogService.Query:output_type -> logengine.QueryResponse
	1, // 4: logengine.LogService.StreamQuery:output_type -> logengine.LogEntry
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_logservice_proto_init() }
func file_proto_logservice_proto_init() {
	if File_proto_logservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logservice_proto_rawDesc), len(file_proto_logservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logservice_proto_goTypes,
		DependencyIndexes: file_proto_logservice_proto_depIdxs,
		MessageInfos:      file_proto_logservice_proto_msgTypes,
	}.Build()
	File_proto_logservice_proto = out.File
	file_proto_logservice_proto_goTypes = nil
	file_proto_logservice_proto_depIdxs = nil
}
